music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:new, :index]

end

music_app/app/models/album.rb
class Album < ApplicationRecord
  validates :name, :band_id, :studio_recording, presence: true

  belongs_to :band,
    primary_key: :id,
    foreign_key: :band_id,
    class_name: :Band
end

music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

music_app/app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :albums,
    primary_key: :id,
    foreign_key: :band_id,
    class_name: :Album
end

music_app/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#


class User < ApplicationRecord
  validates :email, :session_token, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}
  before_validation :ensure_session_token

  attr_reader :password

  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end

  def self.find_by_credentials(email, password)
    user = User.where(email: email).first
    user && user.is_password?(password) ? user : nil
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(pw)
    @password = pw
    self.password_digest = BCrypt::Password.create(pw)
  end

  def is_password?(pw)
    BCrypt::Password.new(self.password_digest).is_password?(pw)
  end


end

music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :require_login

  def new
    @bands = Band.all
    render :new
  end

  def create
    album = Album.new(album_params)
    if album.save
      redirect_to album_url(album)
    else
      redirect_to band_albums_url
    end
  end

  def edit
    @album = Album.find(params[:id])
    @bands = Band.all
    render :edit
  end

  def update
    album = Album.find(params[:id])
    updated_album = album.update(album_params)
    if album.save
      redirect_to album_url(album)
    else
      redirect_to albums_url
    end
  end

  def show
    @album = Album.find(params[:id])
    @band = Band.find(@album.band_id)
    render :show
  end

  def destroy
    album = Album.find(params[:id])
    band = Band.find(album.band_id)
    album.destroy
    redirect_to band_url(band)
  end

  private
  def album_params
    params.require(:albums).permit(:name, :band_id)
  end

  def require_login
    unless current_user
      redirect_to new_session_url
    end
  end
end

music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #current_user to return the current user.
  #logged_in? to return a boolean indicating whether someone is signed in.
  #log_in_user!(user) reset the users session token and cookie

  helper_method :current_user

  def current_user
    User.find_by(session_token: session[:session_token])
  end

  def logged_in?(user)
    current_user == user
  end

  def log_in_user!(user)
    new_token = user.reset_session_token!
    session[:session_token] = new_token
  end
end

music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :require_login
  
  def index
    @bands = Band.all
    render :index
  end

  def new
    render :new
  end

  def create
    band = Band.new(band_params)
    if band.save
      redirect_to band_url(band)
    else
      redirect_to bands_url
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    band = Band.find(params[:id])
    updated_band = band.update(band_params)
    if band.save
      redirect_to band_url(band)
    else
      redirect_to bands_url
    end
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def destroy
    band = Band.find(params[:id])
    band.destroy
    redirect_to bands_url
  end

  private
  def band_params
    params.require(:bands).permit(:name)
  end

  def require_login
    unless current_user
      redirect_to new_session_url
    end
  end
end

music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.find_by_credentials(user_params[:email], user_params[:password])
    if user
      log_in_user!(user)
      redirect_to user_url(user)
    else
      render json: "Invalid Credentials"
    end
  end

  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end

  private

  def user_params
    params.require(:users).permit(:email, :password)
  end

end

music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render :new
  end

  def create
    user = User.create(user_params)

    if user.save
      redirect_to user_url(user)
    else
      redirect_to new_user_url
    end
  end

  def show
    if current_user
      render :show
    else
      redirect_to new_session_url
    end
  end

  private
  def user_params
    params.require('users').permit(:email, :password)
  end
end

music_app/app/helpers/application_helper.rb
module ApplicationHelper
end

music_app/app/views/albums/_album_form.html.erb
<% if thing == 'newalbum' %>
  <% header_message = "list an album" %>
  <% action_url = albums_url %>
  <% name_value = "" %>
  <% band_value = "" %>
  <% submit_value = "List!" %>
  <% selected_value = "" %>
  <% checked_value = "" %>
<% elsif thing == 'editalbum' %>
  <% header_message = "edit an album" %>
  <% action_url = album_url(album) %>
  <% name_value = album.name %>
  <% band_value = "" %>
  <% submit_value = "Edit!" %>
  <% selected_value = "selected" %>
  <% checked_value = 'checked'%>
<% end  %>

<h1> <%= header_message %> </h1>
<form class="" action="<%= action_url %>" method="post">
  <% if thing == 'editalbum' %>
    <input type="hidden" name="_method" value="patch">
  <% end %>

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Album Name:
  <input type="text" name="albums[name]" value="<%= name_value %>">
  </label> <br>

  <label>Band:
  <select class="" name="albums[band_id]">
    <option disabled selected>==SELECT A BAND==</option>
    <% bands.each do |band| %>
      <option value="<%= band.id %>"
        <% if thing == 'newalbum' %>
        <%= "" %>
        <% elsif band.id == album.band_id %>
        <%= "selected" %>
        <% end %>
        > <%= band.name %> </option>
    <% end %>
  </select>
  </label> <br>

  <label>Studio or Live Album?
  <input type="radio" name="albums[studio_recording]" value="true"
    <% if thing == 'newalbum' %>
    <%= "" %>
    <% elsif album.studio_recording %>
    <%= "checked" %>
    <% end %>
    > Studio
  <input type="radio" name="albums[studio_recording]" value="false"
    <% if thing == 'newalbum' %>
    <%= "" %>
    <% elsif album.studio_recording == false %>
    <%= "checked" %>
    <% end %>
   >Live <br>
  </label>

  <input type="submit" name="" value="<%= submit_value %>">
</form>






















.....

music_app/app/views/albums/edit.html.erb
<%= render 'album_form', thing: 'editalbum', album: @album, bands: @bands %>

music_app/app/views/albums/index.html.erb
<% band = @band %>

<h1>All the band's album</h1>
Band Name: <%= band.name %> <br>
<h2> albums </h2>
<% band.albums.each do |album| %>
  <a href="<%= album_url(album) %>"> <%= album.name %> </a> <br>
<% end %>
<br>
<br>
<a href="<%= new_album_url %>"> Add an album </a>

music_app/app/views/albums/new.html.erb
 <%= render 'album_form', thing: 'newalbum', bands: @bands %>

music_app/app/views/albums/show.html.erb
<% album = @album %>
<% band = @band %>

<h2> Album Name: <%= album.name %> </h2>
<h2> Band Name: <%= band.name %> </h2>

<a href="<%= edit_album_url %>">Edit album info</a> <br> <br>

<form action="<%= album_url(album) %>" method="post">
  <input type="hidden" name="_method" value="delete">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="submit" name="" value="delete album">
</form>

<br>
<br>
<a href="<%= band_url(band) %>"> Back to the band's page</a>

music_app/app/views/bands/_band_form.html.erb
<% if thing == 'newband' %>
  <% header_message = "list a band" %>
  <% action_url = bands_url %>
  <% name_value = "" %>
  <% submit_value = "List!" %>
<% elsif thing == 'editband' %>
  <% header_message = "edit a band" %>
  <% action_url = band_url(band) %>
  <% name_value = band.name %>
  <% submit_value = "Edit!" %>
<% end  %>

<h1> <%= header_message %> </h1>
<form class="" action="<%= action_url %>" method="post">
  <% if thing == 'editband' %>
    <input type="hidden" name="_method" value="patch">
  <% end %>

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Band Name:
  <input type="text" name="bands[name]" value="<%= name_value %>">
  </label> <br>

  <input type="submit" name="" value="<%= submit_value %>">
</form>

music_app/app/views/bands/edit.html.erb
<%= render 'band_form', thing: 'editband', band: @band %>

music_app/app/views/bands/index.html.erb
<h1>All the bands</h1>
<% @bands.each do |band| %>
  <a href="<%= band_url(band) %>"> <%= band.name %> </a> <br>
<% end %>
<br>
<br>
<a href="<%= new_band_url %>"> Make a band </a>

music_app/app/views/bands/new.html.erb
 <%= render 'band_form', thing: 'newband' %>

music_app/app/views/bands/show.html.erb
<% band = @band %>
<div class = 'bandinfo'>
<h2> Name: <%= band.name %> </h2>

<h2>Albums: </h2>
<ul>
<% band.albums.each do |album| %>
  <li><a href="<%= album_url(album) %>"> <%= album.name %> <br> </a></li>
<% end %>
</ul>

<br>
<a href="<%= new_band_album_url(band) %>"> Add an album </a><br>

<a href="<%= edit_band_url %>">Edit band info</a> <br> <br>
<form action="<%= band_url(band) %>" method="post">
  <input type="hidden" name="_method" value="delete">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="submit" name="" value="delete band">
</form>

<br>
<br>
<a href="<%= bands_url %>"> Back to all the bands </a>

</div>

music_app/app/views/layouts/_userform.html.erb
<% if thing == 'signup' %>
  <% header_message = "sign up for an account" %>
  <% action_url = users_url %>
  <% submit_value = "SIGN UP" %>
<% elsif thing == 'login' %>
  <% header_message = "Log in" %>
  <% action_url = session_url %>
  <% submit_value = "LOG IN" %>
<% end  %>



<form class="userform" action="<%= action_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Email:
  <input type="text" name="users[email]" value="">
</label> <br><br>

  <label>Password:
  <input type="password" name="users[password]" value="">
</label> <br><br>

  <input type="submit" name="" value="<%= submit_value %>">
</form>

music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>

<%= stylesheet_link_tag "application" %>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1 class = 'logo'> Music App </h1>
      <h1 class = 'accountstuff'> <% if current_user %>
          <form class="" action=" <%= session_url %>" method="post">
            <input type="hidden" name="authenticity_token" value="form_authenticity_token">
            <input type="hidden" name="_method" value="delete">
            <input type="submit" name="" value="Log Out">
          </form>
      <% else %>
        <a href="<%= new_session_url %>"> Log In </a>
        <a href="<%= new_user_url %>"> Sign Up </a>
      <% end %> </h1>
    </header>
      <section>
      <%= yield %>
      </section>
  </body>
</html>

music_app/app/views/users/new.html.erb
<%= render 'layouts/userform', thing: 'signup' %> 

music_app/app/views/users/show.html.erb
<%= current_user.email %>